changelog:
  categories:
    - title: Features
      labels:
        - "*"
      exclude:
        labels:
          - chore
          - dependencies
    - title: Chore
      labels:
        - chore
    - title: Dependencies
      labels:
        - dependencies
